# 8 Graham-Schmidt

In [240]:
import numpy as np

#test inputs for part b and c
A = np.array([[-1 , 2, -1], [-2, 1, -3], [ 1, 3, -2], [-3, 1, 2]])
B = np.array([[1 , 2, 3], [2, 1, 3], [ -1, 3, 2], [3, 6, 9]])

### a)

In [241]:
def gramschmidt(X):
    '''
    Decomposes X into two matrices Q and R such that X = QR where R is a staircase matrix
    and columns of Q consist of k orthonormal vectors q1, q2, . . . , qk such that,
    span(q1,q2,...,qk) = span(x1,x2,...,xn).
    
    Parameter(s):
    X: a matrix with columns 
    
    Returns:
    Two matrices Q and R
    '''
    m,n = np.shape(X)
    Q = np.zeros((m, n))
    #computing the first unit vector q1
    Q[:,0] = X[:,0]/np.power(np.dot(X[:,0],X[:,0]), 0.5) 
    count = 1
    for i in range(1,n):
        q = X[:,i]
        for j in range(i):
            #computing the ith unit vector
            q = q - np.dot(X[:,i],Q[:,j])*Q[:,j]
        #normalizing the ith vector
        if(abs(np.dot(q,q))>0.00000001): 
            Q[:,count] =  q/np.power(np.dot(q,q), 0.5)
            count = count + 1
   
    Q = Q[:,0:count]  #remove redundant columns
    R = np.zeros((count,n))
    
    #populate matrix R
    for i in range (count):
        R[i][i] = np.inner(X[:,i], Q[:,i])
        for j in range (i+1,n):
                R[i,j] = np.inner(Q[:,i], X[:,j])
    return Q, R

### b) 

In [242]:
#complete the span thing

my_QA, my_RA = gramschmidt(A)
rank_original = np.linalg.matrix_rank(A)
rank_gs  = np.linalg.matrix_rank(Z[0])
#because we decompose A to get Q and R so to check if the spans agree we need 
#to check that rank of Q is equal to rank of A
if(rank_original == rank_gs):
    print("Spans agree\n")
print(f'gramschmidt(\n{A})\n\nReturns:\nQ:\n{my_QA}\n\nR:\n{my_RA}')

gramschmidt(
[[-1  2 -1]
 [-2  1 -3]
 [ 1  3 -2]
 [-3  1  2]])

Returns:
Q:
[[-0.25819889  0.46435976  0.02510336]
 [-0.51639778  0.12501993 -0.82283227]
 [ 0.25819889  0.87513954  0.06973155]
 [-0.77459667  0.05357997  0.56343091]]

R:
[[ 3.87298335 -1.03279556 -0.25819889]
 [ 0.          3.73273805 -2.4825387 ]
 [ 0.          0.          3.43079217]]


### c)

In [243]:
my_QB, my_RB = gramschmidt(B)
rank_original = np.linalg.matrix_rank(B)
rank_gs  = np.linalg.matrix_rank(Z[0])

#because we decompose B to get Q and R so to check if the spans agree we need 
#to check that rank of Q is equal to rank of B
if(rank_original == rank_gs):
    print("Spans agree\n")
    
print(f'gramschmidt(\n{B})\n\nReturns:\nQ:\n{my_QB}\n\nR:\n{my_RB}')

Spans agree

gramschmidt(
[[ 1  2  3]
 [ 2  1  3]
 [-1  3  2]
 [ 3  6  9]])

Returns:
Q:
[[ 0.25819889  0.14400324]
 [ 0.51639778 -0.30109768]
 [-0.25819889  0.83783702]
 [ 0.77459667  0.43200971]]

R:
[[3.87298335 4.90577891 8.77876225]
 [0.         5.09247811 5.09247811]]


### d) Read up on the function qr (in MATLAB or Python) from the documentation. Use this function to calculate the orthonormal bases for the subspaces in parts (b) and (c), and verify that these outputs match the outputs of the function in (a). In case they do not, in what way are they different?

In [244]:
Q_A, R_A = np.linalg.qr(A)
Q_B, R_B = np.linalg.qr(B)

In [245]:
print(f'Q-R decomposition for matrix A:\n\nQ_A=\n{Q_A}\n\nR_A=\n{R_A}')

Q-R decomposition for matrix A:

Q_A=
[[-0.25819889  0.46435976  0.02510336]
 [-0.51639778  0.12501993 -0.82283227]
 [ 0.25819889  0.87513954  0.06973155]
 [-0.77459667  0.05357997  0.56343091]]

R_A=
[[ 3.87298335 -1.03279556 -0.25819889]
 [ 0.          3.73273805 -2.4825387 ]
 [ 0.          0.          3.43079217]]


In [246]:
print(f'Q-R decomposition for matrix B:\n\nQ_B=\n{Q_B}\n\nR_B=\n{R_B}')

Q-R decomposition for matrix B:

Q_B=
[[-0.25819889  0.14400324 -0.04108703]
 [-0.51639778 -0.30109768 -0.79132982]
 [ 0.25819889  0.83783702 -0.47479789]
 [-0.77459667  0.43200971  0.38298293]]

R_B=
[[-3.87298335e+00 -4.90577891e+00 -8.77876225e+00]
 [ 0.00000000e+00  5.09247811e+00  5.09247811e+00]
 [ 0.00000000e+00  0.00000000e+00 -5.75118687e-16]]


We observe that Q_A and my_QA are equal and so are corresponding values of R_A and my_RA, but we observe an interesting discrepancy in B, note here that we can easily see that the third column of B is a linear combination of the first two columns, so when we apply grahamschmidt on matrix B we remove the redundant column, but the built-in methods are programmed to return $Q_(mxk)$  and $R_(kxn)$ hence the values that we observe in the third column of Q_B from what has been returned by the built ins make no sense, we can also observe that the third row of R_B has entried that are zeros as -5.75118687e-16 is of the order of 10 to the power 16 which will be extremely small so we can consider it to be 0. This indicates that the third column of Q_B is actually just a consequence of the construct of the built-in function and that those values do not give us any useful information. 